### PR TITLE
Math Magicians: setup

### PR DESCRIPTION
**Pull request by ogagaoghene**
# Math Magicians Setup

## Description 
The environment and tools needed to develop Math Magicians - A React application is setup.

### CODE REVIEW

**Review by Davidosky007 — COMMENTED** [review]
Hi @ogagaoghene 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doest have a descriptive readme file, kindly customise [this readme template](https://github.com/microverseinc/readme-template/blob/master/README.md) to suit your project and submit for another review 🙏 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ogagaoghene** [comment]
Many thanks to you. I have provided a descriptive README.md

**Review by Ghiftee — APPROVED** [review]
## STATUS: APPROVED ♻️♻️
Hi @ogagaoghene, 

Great job implementing all the project's requirements. Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

**Comment by ogagaoghene** [comment]
Thank you

**Pull request merged**
